### ISSUE TITLE
doesn't build on 8.2

### ISSUE THREAD

**Issue by cartazio** [konn/computational-algebra#4]
Hello! 
this lib sadly doesn't seem to build on ghc 8.2
in some cases this may be because of dependencies. If theres any way I or other hackage trustees can help make it happen do let me or other know via the tools / issue tracker over at https://github.com/haskell-infra/hackage-trustees/ 

many thanks!
-Carter

**Comment by konn** [comment]
Thank you for your report!
I'm currently undertaking a process to support GHC 8.2 in my type-level programming packages.
Almost all done, but my [`ghc-typelits-presburger`](/konn/ghc-typelits-presburger) won't behave as expected, and `computational-algebra` deeply relies on it. So please wait until I fix that package.
Thanks again!

**Comment by konn** [comment]
Now fixed. Thank you @cartazio for reporting!
